options:
  docker: true

clone:
  lfs: true

pipelines:
  branches:  # Pipelines that run automatically on a commit to a branch
    dev:
      - step:
          image: atlassian/default-image:2
          name: Run deployment by werf
          deployment: Kubernates
          script:
            - ssh -p $PORT $USERNAME@$HOST 'bash -s' < deployment.sh $SERVICE_HOME $BITBUCKET_BRANCH
          services:
            - docker
    develop:
      - step:
          name: develop
          deployment: test
          script:
            - SSH_CMD="ssh -p $PORT $USERNAME@$HOST"
            - $SSH_CMD "cd $DIR_HOME/src/websocket-service/websocket-service && git checkout -- . && git pull"
            - $SSH_CMD "cd $DIR_HOME && bin/docker-build.sh msg"
            - $SSH_CMD "cd $DIR_HOME && bin/docker-reload.sh"
            - $SSH_CMD "cd $DIR_HOME && bin/docker-consumer.sh"

    staging:
      - step:
          name: staging deployment
          deployment: staging
          script:
            - SSH_CMD="ssh -p $PORT $USERNAME@$HOST"
            - $SSH_CMD "cd $DIR_HOME && git checkout -- . && git checkout staging && git pull origin staging"
            - $SSH_CMD "cd $DIR_HOME && go mod download"
            - $SSH_CMD "cd $DIR_HOME && go mod tidy"
            - $SSH_CMD "cd $DIR_HOME && go build ."
            - $SSH_CMD "cd $DIR_HOME && mv websocket-service /home/magerya/go/bin/"
            - $SSH_CMD "sudo supervisorctl restart websocket:*"

    master:
      - step:
          name: production deployment
          deployment: production
          script:
            - SSH_CMD="ssh -p $PORT $USERNAME@$HOST"
            - $SSH_CMD "cd $DIR_HOME && git checkout -- . && git checkout master && git pull origin master"
            - $SSH_CMD "cd $DIR_HOME && go mod download"
            - $SSH_CMD "cd $DIR_HOME && go mod tidy"
            - $SSH_CMD "cd $DIR_HOME && go build ."
            - $SSH_CMD "cd $DIR_HOME && mv websocket-service /home/magerya/go/bin/"
            - $SSH_CMD "sudo supervisorctl restart websocket:*"