apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "websocket_service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

data:
{{ (tpl (.Files.Glob "configs/config.json").AsConfig . ) | indent 2 }}





