apiVersion: v1
kind: Service
metadata:
  name: {{ include "websocket_service.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "websocket_service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.websocket_service.service.type }}
  ports:
    - port: {{ .Values.websocket_service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "websocket_service.websocket_service.selectorLabels" . | nindent 4 }}
